Document: projectm
Title: Debian projectm Manual
Author: <insert document author here>
Abstract: This manual describes what projectm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/projectm/projectm.sgml.gz

Format: postscript
Files: /usr/share/doc/projectm/projectm.ps.gz

Format: text
Files: /usr/share/doc/projectm/projectm.text.gz

Format: HTML
Index: /usr/share/doc/projectm/html/index.html
Files: /usr/share/doc/projectm/html/*.html
